### ISSUE TITLE
amazon_reviews_multi no longer available on HuggingFace

### ISSUE THREAD

**Issue by brianloyal** [aws-neuron/aws-neuron-sagemaker-samples#3]
The amazon_reviews_multi is no longer available on HuggingFace (https://huggingface.co/datasets/amazon_reviews_multi/discussions/4#64c3898db63057f1fd3ce1a0). So, we'll need to use a different dataset for this training example:

training/trn1-bert-fine-tuning-on-sagemaker/bert-base-uncased-amazon-reviews.ipynb

**Comment by AWShtokoyo** [comment]
Fixed.

**Comment by AWShtokoyo** [comment]
Fixed
