### ISSUE TITLE
Language cleanup

### ISSUE THREAD

**Issue by brianloyal** [aws-neuron/aws-neuron-sagemaker-samples#4]
The `random_sentence()` function used for benchmarking in the "inference/inf2-bert-on-sagemaker/inf2_bert_sagemaker.ipynb" notebook contains some potentially offensive random terms. Can we please replace those?

![image](https://github.com/aws-neuron/aws-neuron-sagemaker-samples/assets/94650726/abd5ff4f-532e-445d-bd22-20d181eb4ec9)

**Comment by jeffhataws** [comment]
Thanks @brianloyal . Will work on this.
